# ===== Database Configuration =====
spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false   


# ===== Server Configuration =====
server.forward-headers-strategy=framework


# ===== Gemini AI Configuration =====
spring.ai.openai.base-url=https://generativelanguage.googleapis.com/v1beta/openai/
spring.ai.openai.api-key=${GEMINI_API_KEY}
spring.ai.openai.chat.options.model=gemini-3-flash-preview

# ===== YouTube API Configuration =====
youtube.api.key=${YOUTUBE_API_KEY}

# ===== Google Maps API Configuration =====
google.maps.api.key=${GOOGLE_MAPS_API_KEY}

# Logging Configuration
logging.level.org.springframework=INFO
# Also log your own code's activity
logging.level.com.legal=INFO
# Save logs to a file so they aren't lost
logging.file.name=logs/welegal.log
# Automatically archive old logs when they reach 10MB
logging.logback.rollingpolicy.max-file-size=10MB

# How many connections can stay open at once (Default is 10)
spring.datasource.hikari.maximum-pool-size=15
# How long a user should wait for a connection before giving up (30 seconds)
spring.datasource.hikari.connection-timeout=30000
# Minimum number of connections to keep idle (ready to go)
spring.datasource.hikari.minimum-idle=5
# How long a connection can stay "awake" before being refreshed
spring.datasource.hikari.max-lifetime=1800000

# ==== Session Configuration
# Increase session timeout to 4 hours (240 minutes)
server.servlet.session.timeout=240m
server.servlet.session.cookie.max-age=240m
