# ===== Database Configuration =====
spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=create
spring.jpa.open-in-view=false   


# ===== Server Configuration =====

server.forward-headers-strategy=framework


# ===== Gemini AI Configuration =====
spring.ai.openai.base-url=https://generativelanguage.googleapis.com/v1beta/openai/
spring.ai.openai.api-key=${GEMINI_API_KEY}
spring.ai.openai.chat.options.model=gemini-3-flash-preview

# ===== YouTube API Configuration =====
youtube.api.key=${YOUTUBE_API_KEY}

# ===== Google Maps API Configuration =====
google.maps.api.key=${GOOGLE_MAPS_API_KEY}


